// Command sumeru-import-gen writes a Go file of blank imports for all strict addons
// discovered via INI addons_path (default: cmd/sumeru/zimports.go, package main for in-repo builds).
// For an external workspace (e.g. sumeru_custom_addons), use -package and -out to write
// only side-effect imports outside the standard sumeru tree.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"sumeru/core/module"
	"sumeru/core/server/config"
)

var outputPackagePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func main() {
	outPath := flag.String("out", "cmd/sumeru/zimports.go", "output .go path: relative to -root/repo, or absolute")
	configPath := flag.String("config", "sumeru.conf", "INI path: relative to repo root, or absolute")
	repoRootFlag := flag.String("root", "", "sumeru repo root (directory with go.mod); default: search upward from cwd")
	packageName := flag.String("package", "main", "generated file package name (e.g. main or addonimports)")
	flag.Parse()

	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	repoRoot := strings.TrimSpace(*repoRootFlag)
	if repoRoot == "" {
		repoRoot, err = module.FindRepoRoot(cwd)
		if err != nil {
			fmt.Fprintf(os.Stderr, "sumeru-import-gen: %v (use -root)\n", err)
			os.Exit(1)
		}
	} else {
		repoRoot, err = filepath.Abs(repoRoot)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}

	dest, err := runGen(repoRoot, *configPath, *outPath, *packageName)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sumeru-import-gen: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(dest)
}

func validateOutputPackage(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("empty -package")
	}
	if !outputPackagePattern.MatchString(name) {
		return fmt.Errorf("package %q must match %s", name, outputPackagePattern.String())
	}
	return nil
}

func resolveOutputPath(repoRoot, outPath string) (string, error) {
	outPath = strings.TrimSpace(filepath.FromSlash(outPath))
	if outPath == "" {
		return "", fmt.Errorf("empty -out")
	}
	if filepath.IsAbs(outPath) {
		return filepath.Clean(outPath), nil
	}
	return filepath.Clean(filepath.Join(repoRoot, outPath)), nil
}

func configPathForLoad(repoRoot, configPath string) string {
	configPath = strings.TrimSpace(filepath.FromSlash(configPath))
	if configPath == "" {
		return filepath.Join(repoRoot, "sumeru.conf")
	}
	if filepath.IsAbs(configPath) {
		return filepath.Clean(configPath)
	}
	return filepath.Clean(filepath.Join(repoRoot, configPath))
}

func buildImportGoFile(packageName string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\npackage ")
	b.WriteString(packageName)
	b.WriteString("\n\nimport (\n")
	for _, p := range imports {
		b.WriteString("\t_ \"")
		b.WriteString(p)
		b.WriteString("\"\n")
	}
	b.WriteString(")\n")
	return b.String()
}

func runGen(repoRoot, configPath, outPath, packageName string) (written string, err error) {
	if err := validateOutputPackage(packageName); err != nil {
		return "", err
	}
	repoRoot, err = filepath.Abs(repoRoot)
	if err != nil {
		return "", err
	}
	dest, err := resolveOutputPath(repoRoot, outPath)
	if err != nil {
		return "", err
	}

	cfg := configPathForLoad(repoRoot, configPath)
	cfgAbs, err := filepath.Abs(cfg)
	if err != nil {
		return "", fmt.Errorf("config path: %w", err)
	}

	if err := config.LoadConfig(cfgAbs); err != nil {
		return "", fmt.Errorf("load config: %w", err)
	}
	if err := config.AbsPaths(); err != nil {
		return "", fmt.Errorf("abs paths: %w", err)
	}

	discovered, err := module.DiscoverAddonRoots(config.AppConfig.AddonPaths)
	if err != nil {
		return "", fmt.Errorf("discover: %w", err)
	}
	if err := module.ValidateDiscoveredAddons(discovered); err != nil {
		return "", fmt.Errorf("convention: %w", err)
	}

	imports, err := module.AddonImportPaths(discovered)
	if err != nil {
		return "", err
	}

	body := buildImportGoFile(packageName, imports)
	dir := filepath.Dir(dest)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", dest, err)
	}
	return dest, nil
}
