// Package importgen implements sumeru-import-gen logic so it can be tested from sumeru/test.
package importgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"sumeru/core/module"
	"sumeru/core/server/config"
)

var outputPackagePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// ValidateOutputPackage checks -package is a valid Go package identifier for generated imports.
func ValidateOutputPackage(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("empty -package")
	}
	if !outputPackagePattern.MatchString(name) {
		return fmt.Errorf("package %q must match %s", name, outputPackagePattern.String())
	}
	return nil
}

// ResolveOutputPath returns an absolute path for the generated file.
func ResolveOutputPath(repoRoot, outPath string) (string, error) {
	outPath = strings.TrimSpace(filepath.FromSlash(outPath))
	if outPath == "" {
		return "", fmt.Errorf("empty -out")
	}
	if filepath.IsAbs(outPath) {
		return filepath.Clean(outPath), nil
	}
	return filepath.Clean(filepath.Join(repoRoot, outPath)), nil
}

func configPathForLoad(repoRoot, configPath string) string {
	configPath = strings.TrimSpace(filepath.FromSlash(configPath))
	if configPath == "" {
		return filepath.Join(repoRoot, "sumeru.conf.example")
	}
	if filepath.IsAbs(configPath) {
		return filepath.Clean(configPath)
	}
	return filepath.Clean(filepath.Join(repoRoot, configPath))
}

// BuildImportGoFile renders the blank-import Go source.
func BuildImportGoFile(packageName string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\npackage ")
	b.WriteString(packageName)
	b.WriteString("\n\nimport (\n")
	for _, p := range imports {
		b.WriteString("\t_ \"")
		b.WriteString(p)
		b.WriteString("\"\n")
	}
	b.WriteString(")\n")
	return b.String()
}

// RunGen loads config, discovers addons, and writes the import file to dest.
func RunGen(repoRoot, configPath, outPath, packageName string) (written string, err error) {
	if err := ValidateOutputPackage(packageName); err != nil {
		return "", err
	}
	repoRoot, err = filepath.Abs(repoRoot)
	if err != nil {
		return "", err
	}
	dest, err := ResolveOutputPath(repoRoot, outPath)
	if err != nil {
		return "", err
	}

	cfg := configPathForLoad(repoRoot, configPath)
	cfgAbs, err := filepath.Abs(cfg)
	if err != nil {
		return "", fmt.Errorf("config path: %w", err)
	}

	if err := config.LoadConfig(cfgAbs); err != nil {
		return "", fmt.Errorf("load config: %w", err)
	}
	if err := config.AbsPaths(); err != nil {
		return "", fmt.Errorf("abs paths: %w", err)
	}

	discovered, err := module.DiscoverAddonRoots(config.AppConfig.AddonPaths)
	if err != nil {
		return "", fmt.Errorf("discover: %w", err)
	}
	if err := module.ValidateDiscoveredAddons(discovered); err != nil {
		return "", fmt.Errorf("convention: %w", err)
	}

	imports, err := module.AddonImportPaths(discovered)
	if err != nil {
		return "", err
	}

	body := BuildImportGoFile(packageName, imports)
	dir := filepath.Dir(dest)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", dest, err)
	}
	return dest, nil
}
