package importgen

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

var outputPackagePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// ValidateOutputPackage checks -package is a valid Go package identifier for generated imports.
func ValidateOutputPackage(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("empty -package")
	}
	if !outputPackagePattern.MatchString(name) {
		return fmt.Errorf("package %q must match %s", name, outputPackagePattern.String())
	}
	return nil
}

// ResolveOutputPath returns an absolute path for the generated file.
func ResolveOutputPath(repoRoot, outPath string) (string, error) {
	outPath = strings.TrimSpace(filepath.FromSlash(outPath))
	if outPath == "" {
		return "", fmt.Errorf("empty -out")
	}
	if filepath.IsAbs(outPath) {
		return filepath.Clean(outPath), nil
	}
	return filepath.Clean(filepath.Join(repoRoot, outPath)), nil
}

func configPathForLoad(repoRoot, configPath string) string {
	configPath = strings.TrimSpace(filepath.FromSlash(configPath))
	if configPath == "" {
		return filepath.Join(repoRoot, "sumeru.conf.example")
	}
	if filepath.IsAbs(configPath) {
		return filepath.Clean(configPath)
	}
	return filepath.Clean(filepath.Join(repoRoot, configPath))
}

// BuildImportGoFile renders the blank-import Go source.
func BuildImportGoFile(packageName string, imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by sumeru-import-gen; DO NOT EDIT.\n\npackage ")
	b.WriteString(packageName)
	b.WriteString("\n\nimport (\n")
	for _, p := range imports {
		b.WriteString("\t_ \"")
		b.WriteString(p)
		b.WriteString("\"\n")
	}
	b.WriteString(")\n")
	return b.String()
}
