// Package sdk is the stable surface for addon and integration code.
//
// Define models as structs embedding sdk.Model with typed fields (sdk.String,
// sdk.Many2One[T], …) and optional `sumeru` struct tags. Registration is
// generated by `make generate` into models/zmodels.go.
//
// Public API:
//   - sdk.Model embed and typed field markers (String, Integer, Float, Float64, …)
//   - Relations: Many2One[T], One2Many[T], Many2Many[T] — use concrete model types
//     in the same module, or generated zrefs types for cross-module relations
//   - sdk.Selection[T] — options auto-discovered from typed const blocks
//   - Search, Create, Upsert, InitDB, SyncModels (see query.go, db.go)
package sdk
