// Code generated by sumeru-import-gen; DO NOT EDIT.

package models

import (
	coreorm "sumeru/core/orm"
)

// SysModuleCategory → sys.module.category
type SysModuleCategory = coreorm.SysModuleCategory

